### PR TITLE
Fix layout + cleanup

### PR DESCRIPTION
**Pull request by ZeroGDesign**
Fixing the Just the Docs layout,

Removing a ton of files that are included in just the docs and don't need to be there seperate (causing issues).

Installed the new logo + fav icon.

### CODE REVIEW

**Comment by HumbleDeer** [comment]
Hi!

Could you please clarify the reason for removing a plugin I recently intentionally added?

Can you clarify what was wrong in the layout? Did it have to do with the update to Just The Docs 0.6, and if so, does reverting to version 0.4 fix this?

I left out Faraday in the past, as its features didn't seem to pose a benefit for building in the GH runners. Can you explain what adding it back again does better?

I generally don't regularly update the gemlock, because the minor updates to many of the libraries don't really project any improvement and would merely end up clogging our git history. I update it when I am changing something else in the gemfile. :)

Thanks for your contributions!

**Comment by ZeroGDesign** [comment]
No problem:

> Could you please clarify the reason for removing a plugin I recently intentionally added?

As far as I can see the plugin isn't being used.

> Can you clarify what was wrong in the layout? Did it have to do with the update to Just The Docs 0.6, and if so, does reverting to version 0.4 fix this?

Sure, the initial layout was missing a lot of css/scss classes. This caused the layout to not display properly and not scale properly. Here is an example on how it should look  We're not reverting the layout to an older version at all. The new version has loads of new features and fixes that are very nice.

> I generally don't regularly update the gemlock, because the minor updates to many of the libraries don't really project any improvement and would merely end up clogging our git history. I update it when I am changing something else in the gemfile. :)

it seems that the `Gemfile.lock` was still displaying `just-the-docs (0.4.2)` indicating it wasn't updated with the layout, this doesn't seem like a minor update. Updating the gemfile using the `bundle install` command will grab your file `Gemfile` and install everything that is needed updating the `Gemfile.lock` to a newer version. I wouldn't worry to much about small changes either. But this is the main reason for the change.

> Faraday 

Was in your Gemfile already, just updated it. To my knowledge is used to run your local copy of jekyll/just the docs on your desktop so you can simulate it before you upload it to the Github Pages.

**Comment by HumbleDeer** [comment]
Do you have an image of what the broken layout was like? The image you included shows a layout identical or at least very close to what I've always seen. If something broke when I updated to just the docs 0.6 then that would be good to know :)

The plugin that seemed unused was being used in a file I was working on locally. I can't show an example of those as I'm currently away from my computer. 

What's up with the pr being closed or the head deleted? Are there issues with the PR you made? Or was it a mistake? If there's any problem I can help sort out, do let me know!

Edit: just to clarify in case I'm not expressing it correctly; I'm not meaning to be condescending or demeaning. I simply want to have done my due diligence as to not simply approve pull requests without knowing what's in them, what the person intended, or what could be accidentally wrong. 😅

Cheers,
HumbleDeer.

**Comment by ZeroGDesign** [comment]
> Do you have an image of what the broken layout was like? The image you included shows a layout identical or at least very close to what I've always seen. If something broke when I updated to just the docs 0.6 then that would be good to know :)

The layout being broken isn't your fault, neither is the update to 0.6. It's the initial setup that is wrong. Adding the scss files to the folder itself makes jekyll not care for a external layout. This caused issues because there are many classes missing.

Here is a screenshot with a small explanation:
 


vs proper scaling


> The plugin that seemed unused was being used in a file I was working on locally. I can't show an example of those as I'm currently away from my computer.

Then my removal of this plugin would be incorrect and it would definitely need to stay

> What's up with the pr being closed or the head deleted? Are there issues with the PR you made? Or was it a mistake? If there's any problem I can help sort out, do let me know!

It's because I didn't want to leave it open as a fork on my profile as this profile is used for the ZeroG Project.
if you want to check that out and see how we do it, it's on docs.zerog.one

**Comment by HumbleDeer** [comment]
I see, thanks for elaborating! And thanks for your contributions. :)

I'm on my way home now, and will be taking a look at my computer.

Thanks,
HumbleDeer

**Pull request closed without merging**
