### PR TITLE
ZeroG theme fixes, optimizations

### PR DESCRIPTION
**Pull request by HumbleDeer**
This PR encompasses the previous pull request by @zerogdesign #77. this PR was closed, because their head repository was deleted. I've created a branch that mirrors their original commits on top of our current head. 

Changes made by ZeroGDesign:

* Removed the bootstrap tabs plugin, presumed not used/not necessary
* Reorganise and add missing Sass/css files that caused theme issues on certain viewport sizes
  (This issue was present since the beginning of the repo's creation)
* Updates dependencies and packages in the gemfile ~~(and inadvertently regressed some?)~~ 
* Updated the logo to a new design

Thanks for your contributions, ZeroGDesign. 

These issues were previously discussed with @pbsuper as stated by themselves.

### CODE REVIEW

**Comment by pbsuper** [comment]
Updates dependencies and packages in the gemfile (and inadvertently regressed some?)

Looking through the PR none if the versions are being set to a older one only newer.

**Comment by HumbleDeer** [comment]
> Looking through the PR none if the versions are being set to a older one only newer.

That's why there was a question mark behind the parenthesized comment. 🙂 It means the state is unknown.

**Comment by HumbleDeer** [comment]
Things I'd still like to figure out before merging this PR:

* Text sizing on mobile is erratic without the reset.scss (and too small, above all).
* Front page (still) not responsive -- should be doable and is worth doing now that other breakpoints are working.
* _having a nap_

Other notes: 

* No packages were regressed in version. Not sure where the update to the version of Just The Docs I did actually got stuck. Probably some other PR somewhere. 
* Moved the styles ZeroG moved into the vzbot color scheme, back out of there. They're not color scheme related in the end, and since I added other custom classes it was worth moving them into the topologically correct place. 
* Added the Bootstrap 5 tabs plugin back, as it's currently being used in my local edit of some otherwise very hard to navigate pages -- it'll be used soon if everything goes right.
* An erroneous img-map.js error crept back in somewhere (not related to ZeroG commits) and I hope to have fixed this one for once and for all by using Jekyll's built in methods for resolving path errors like these.
* Color of the SVG logo's white lettering was changed to an off white to make it slightly less jarring. An additional amount of padding was added both on mobile and desktop to scale it more appropriately as our logo. It felt out of place large before. 🤷🏻 

image
image

**Comment by HumbleDeer** [comment]
Latest commit also adds some slight theme colour scheme changes that improve readability. 

There are still some issues with the layout just around 820px wide, but these may be resolved in the future. They don't pose a major issue in mean time and don't make anything unavailable. 

Test deployment: https://zerog-theme-fixes.vzbot3d-docs.pages.dev/

image

**Review by pbsuper — APPROVED** [review]
Looks good

**Pull request merged**
